# Generated by Django 4.0.2 on 2022-03-02 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Phone'),
        ),
        migrations.CreateModel(
            name='ConfirmResetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=8, null=True, verbose_name='Код подтверждения')),
                ('is_confirmed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Подтверждено')),
                ('time_initial_send_sms', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время последней отправки sms кода')),
                ('expired_time', models.DateTimeField(verbose_name='Время окончания действия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_confirm_password', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подверждение смены пароля',
                'verbose_name_plural': 'Подверждение смены пароля',
            },
        ),
    ]
