# Generated by Django 4.0.2 on 2022-03-02 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone_confirmresetpassword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfirmResetPassword',
            new_name='ConfirmCode',
        ),
        migrations.AlterModelOptions(
            name='confirmcode',
            options={'verbose_name': 'Подверждение кода', 'verbose_name_plural': 'Подверждение кода'},
        ),
    ]
