# Generated by Django 4.0.2 on 2022-03-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_off',
            field=models.BooleanField(blank=True, default=False, verbose_name='Отключение необязательных push уведомлений'),
        ),
    ]
