# Generated by Django 4.0.2 on 2022-04-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_push_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_confirmed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Подтвердил ли пользователь телефон?'),
        ),
    ]
