# Generated by Django 4.0.2 on 2022-08-23 09:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmPassword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=6, verbose_name='Код подтверждения')),
                ('is_confirmed', models.BooleanField(blank=True, default=False, verbose_name='Подтвержденный аккаунт')),
                ('expired_time', models.DateTimeField(null=True, verbose_name='Дата окончания действия')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Подтвержение пароля',
                'verbose_name_plural': 'Подтвержение пароля',
                'ordering': ['expired_time'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmPhone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=6, verbose_name='Код подтверждения')),
                ('is_confirmed', models.BooleanField(blank=True, default=False, verbose_name='Подтвержденный аккаунт')),
                ('expired_time', models.DateTimeField(null=True, verbose_name='Дата окончания действия')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Подтвержение аккаунта',
                'verbose_name_plural': 'Подтвержение аккаунта',
            },
        ),
        migrations.DeleteModel(
            name='ConfirmCode',
        ),
    ]
