# Generated by Django 4.0.4 on 2022-10-12 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_is_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmphone',
            options={'ordering': ['date_created'], 'verbose_name': 'Подтвержение аккаунта', 'verbose_name_plural': 'Подтвержение аккаунта'},
        ),
        migrations.AddField(
            model_name='confirmpassword',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='confirmphone',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
