# Generated by Django 4.0.4 on 2022-12-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_image'),
        ('users', '0015_rename_сountry_user_country_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.File', verbose_name='Аватар'),
        ),
    ]
