# Generated by Django 4.0.4 on 2022-12-26 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_passportfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportfiles',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='passports_files', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
