# Generated by Django 4.0.4 on 2023-01-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_passportfiles_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportfiles',
            name='selfie_with_passport',
            field=models.ImageField(default='qw', upload_to='uploads/passports/', verbose_name='Селви с папортом'),
            preserve_default=False,
        ),
    ]
