# Generated by Django 4.0.4 on 2023-01-22 13:31

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_passportfiles_main_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmMail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=6, verbose_name='Код подтверждения')),
                ('is_confirmed', models.BooleanField(blank=True, default=False, verbose_name='Подтвержденный аккаунт')),
                ('expired_time', models.DateTimeField(null=True, verbose_name='Дата окончания действия')),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
            ],
            options={
                'verbose_name': 'Подтвержение почты',
                'verbose_name_plural': 'Подтвержение почты',
                'ordering': ['expired_time'],
            },
        ),
    ]
