# Generated by Django 4.0.4 on 2023-01-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_confirmmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmmail',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
