# Generated by Django 4.0.4 on 2022-11-29 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0004_alter_offer_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
        ('order', '0004_order_count_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(blank=True, choices=[('created', 'Создан (не подписан)'), ('rejected', 'Отклонен'), ('in_process', 'На выполнении'), ('moderation', 'На проверке'), ('completed', 'Выполнен'), ('for_revision', 'На доработку'), ('dispute', 'Открыт спор')], default='created', max_length=300, verbose_name='Статус')),
                ('signature', models.BooleanField(default=False, verbose_name='Подтвержден?')),
                ('condition', models.CharField(max_length=500, verbose_name='condition')),
                ('amount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='payment.budget')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_customer', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('offer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts_offer', to='offer.offer')),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts_order', to='order.order')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
            },
        ),
    ]
