# Generated by Django 4.0.4 on 2022-11-30 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_count_views'),
        ('offer', '0004_alter_offer_author'),
        ('contract', '0002_alter_contract_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts_offer', to='offer.offer'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts_order', to='order.order'),
        ),
    ]
