# Generated by Django 4.0.4 on 2022-11-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='count',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество/цена??'),
        ),
    ]
