# Generated by Django 4.0.4 on 2022-12-08 03:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_budget_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=300, verbose_name='Метод оплаты')),
            ],
            options={
                'verbose_name': 'Метод оплаты',
                'verbose_name_plural': 'Метод оплаты',
            },
        ),
    ]
