# Generated by Django 4.0.4 on 2022-12-08 04:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=300, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Метод оплаты', 'verbose_name_plural': 'Методы оплаты'},
        ),
        migrations.RemoveField(
            model_name='budget',
            name='currency',
        ),
    ]
