# Generated by Django 4.0.4 on 2023-01-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
