# Generated by Django 4.0.4 on 2022-11-15 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500, verbose_name='Название Предложениеа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.CharField(blank=True, choices=[('draft', 'Черновик'), ('await', 'Ожидает оплаты'), ('blocked', 'Заблокирован'), ('moderation', 'На модерации'), ('deleted', 'Удален'), ('published', 'Опубликован')], default='draft', max_length=300, verbose_name='Статус')),
                ('payment_method', models.CharField(blank=True, choices=[('credit_card', 'Кредитной картой')], default='credit_card', max_length=300, verbose_name='Метод оплаты')),
                ('execution_time', models.DateTimeField(blank=True, null=True, verbose_name='Время исполнения')),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('max_contracts', models.PositiveIntegerField(default=0, verbose_name='Максимальное количество заказчиков')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Offers', to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='payment.budget')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
    ]
