# Generated by Django 4.0.4 on 2022-11-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_alter_offer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='count_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
