# Generated by Django 4.0.4 on 2022-12-08 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_alter_electedoffer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='payment_method',
        ),
    ]
