# Generated by Django 4.0.4 on 2022-12-11 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_currency_short_title'),
        ('offer', '0008_offer_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.budget'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.paymentmethod'),
        ),
    ]
