# Generated by Django 4.0.4 on 2022-12-15 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offer', '0009_alter_offer_budget_alter_offer_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electedoffer',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
