# Generated by Django 4.0.4 on 2022-12-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_currency_short_title'),
        ('offer', '0010_alter_electedoffer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='offer',
            name='budgets',
            field=models.ManyToManyField(to='payment.budget'),
        ),
        migrations.AddField(
            model_name='offer',
            name='payment_methods',
            field=models.ManyToManyField(to='payment.paymentmethod'),
        ),
    ]
