# Generated by Django 4.0.4 on 2023-02-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0012_alter_offer_max_contracts'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Короткое описание'),
        ),
    ]
