# Generated by Django 4.0.4 on 2022-12-26 16:27

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0012_alter_offer_max_contracts'),
        ('order', '0014_alter_order_max_contracts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500, verbose_name='Название подборки')),
                ('sorting_number', models.PositiveSmallIntegerField(blank=True, verbose_name='Сортировочный номер')),
                ('date_create', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('orders', models.ManyToManyField(blank=True, related_name='selections_order', to='order.order')),
            ],
            options={
                'verbose_name': 'Подборка заказа',
                'verbose_name_plural': 'Подборки заказов',
            },
        ),
        migrations.CreateModel(
            name='SelectionOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500, verbose_name='Название подборки')),
                ('sorting_number', models.PositiveSmallIntegerField(blank=True, verbose_name='Сортировочный номер')),
                ('date_create', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('offers', models.ManyToManyField(blank=True, related_name='selections_offer', to='offer.offer')),
            ],
            options={
                'verbose_name': 'Подборка предложения',
                'verbose_name_plural': 'Подборки предложений',
            },
        ),
    ]
