# Generated by Django 4.0.4 on 2022-12-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectionoffer',
            name='sorting_number',
            field=models.PositiveSmallIntegerField(blank=True, unique=True, verbose_name='Сортировочный номер'),
        ),
        migrations.AlterField(
            model_name='selectionorder',
            name='sorting_number',
            field=models.PositiveSmallIntegerField(blank=True, unique=True, verbose_name='Сортировочный номер'),
        ),
    ]
