# Generated by Django 4.0.4 on 2022-12-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0002_alter_selectionoffer_sorting_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectionoffer',
            old_name='date_create',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='selectionorder',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
