# Generated by Django 4.0.4 on 2023-02-06 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0004_delete_image'),
        ('contract', '0005_alter_contract_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(verbose_name='Текст')),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('sent', 'отправлено'), ('read', 'прочитано'), ('error', 'ошибка')], default='sent', max_length=250, verbose_name='Статуc')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('chat_files', models.ManyToManyField(blank=True, null=True, related_name='chat_messages', to='common.file')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чата',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='ItemChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_chat', to='contract.contract', verbose_name='Контракт')),
                ('messages', models.ManyToManyField(blank=True, related_name='items_chat', to='chat.chatmessage', verbose_name='Сообщения')),
            ],
            options={
                'verbose_name': 'Предмет чата',
                'verbose_name_plural': 'Предмет чата',
            },
        ),
        migrations.CreateModel(
            name='MainChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mainchat_customer', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mainchat_executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('items_chat', models.ManyToManyField(related_name='mainchats', to='chat.itemchat')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
    ]
