# Generated by Django 4.0.4 on 2022-11-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
