# Generated by Django 4.0.4 on 2022-11-30 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0004_order_count_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('body_params', models.JSONField(default=dict, verbose_name='Параметры поиска из body')),
                ('date_create', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('type_search', models.CharField(choices=[('order', 'Поиск по заказам'), ('offer', 'Поиск по предложениям')], max_length=50, verbose_name='Тип поиска')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_savedsearch', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сохраненный поиск',
                'verbose_name_plural': 'Сохраненные поиски',
            },
        ),
    ]
