# Generated by Django 4.0.4 on 2022-11-30 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0006_alter_savedsearch_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectedOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_order_elected', to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_user_order_elected', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранный заказ',
                'verbose_name_plural': 'Избранные заказы',
            },
        ),
    ]
