# Generated by Django 4.0.4 on 2022-12-15 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0011_alter_order_budget_alter_order_max_contracts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electedorder',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SavedSearch',
        ),
    ]
