# Generated by Django 4.0.4 on 2023-02-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_max_contracts'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Короткое описание'),
        ),
    ]
